// ============================================================
// NACIONALIDADES
//
// Mapa de país -> código de bandera. Los nombres son los que trae el
// catálogo (dataset FIFA), incluidas sus variantes de escritura.
// Cubre los 163 países presentes en el juego.
//
// Los archivos están en /public/flags como SVG 1:1: pesan poco y se
// ven nítidos en cualquier tamaño, sin versiones @2x.
// ============================================================

const CODES: Record<string, string> = {
  "Afghanistan": "af",
  "Albania": "al",
  "Alemania": "de",
  "Algeria": "dz",
  "Andorra": "ad",
  "Angola": "ao",
  "Antigua and Barbuda": "ag",
  "Argelia": "dz",
  "Argentina": "ar",
  "Armenia": "am",
  "Australia": "au",
  "Austria": "at",
  "Azerbaijan": "az",
  "Bahrain": "bh",
  "Bangladesh": "bd",
  "Barbados": "bb",
  "Belarus": "by",
  "Belgium": "be",
  "Belize": "bz",
  "Benin": "bj",
  "Bermuda": "bm",
  "Bhutan": "bt",
  "Bolivia": "bo",
  "Bosnia and Herzegovina": "ba",
  "Botswana": "bw",
  "Brasil": "br",
  "Brazil": "br",
  "Bulgaria": "bg",
  "Burkina Faso": "bf",
  "Burundi": "bi",
  "Bélgica": "be",
  "Cambodia": "kh",
  "Cameroon": "cm",
  "Camerún": "cm",
  "Canada": "ca",
  "Canadá": "ca",
  "Cape Verde Islands": "cv",
  "Central African Republic": "cf",
  "Chad": "td",
  "Chequia": "cz",
  "Chile": "cl",
  "China": "cn",
  "China PR": "cn",
  "Chinese Taipei": "tw",
  "Colombia": "co",
  "Comoros": "km",
  "Congo": "cg",
  "Congo DR": "cd",
  "Corea": "kr",
  "Costa Rica": "cr",
  "Croacia": "hr",
  "Croatia": "hr",
  "Cuba": "cu",
  "Curacao": "cw",
  "Curaçao": "cw",
  "Cyprus": "cy",
  "Czech Republic": "cz",
  "Côte d'Ivoire": "ci",
  "Denmark": "dk",
  "Dinamarca": "dk",
  "Dominican Republic": "do",
  "Ecuador": "ec",
  "Egipto": "eg",
  "Egypt": "eg",
  "El Salvador": "sv",
  "England": "gb-eng",
  "Equatorial Guinea": "gq",
  "Eritrea": "er",
  "España": "es",
  "Estados Unidos": "us",
  "Estonia": "ee",
  "Ethiopia": "et",
  "Faroe Islands": "fo",
  "Fiji": "fj",
  "Finland": "fi",
  "France": "fr",
  "Francia": "fr",
  "French Guiana": "gf",
  "Gabon": "ga",
  "Gambia": "gm",
  "Georgia": "ge",
  "Germany": "de",
  "Ghana": "gh",
  "Gibraltar": "gi",
  "Grecia": "gr",
  "Greece": "gr",
  "Grenada": "gd",
  "Guadeloupe": "gp",
  "Guam": "gu",
  "Guatemala": "gt",
  "Guinea": "gn",
  "Guinea Bissau": "gw",
  "Guyana": "gy",
  "Haiti": "ht",
  "Honduras": "hn",
  "Hong Kong": "hk",
  "Hungary": "hu",
  "Iceland": "is",
  "India": "in",
  "Indonesia": "id",
  "Inglaterra": "gb",
  "Iran": "ir",
  "Iraq": "iq",
  "Irlanda": "ie",
  "Israel": "il",
  "Italia": "it",
  "Italy": "it",
  "Ivory Coast": "ci",
  "Jamaica": "jm",
  "Japan": "jp",
  "Japón": "jp",
  "Jordan": "jo",
  "Kazakhstan": "kz",
  "Kenya": "ke",
  "Korea DPR": "kp",
  "Korea Republic": "kr",
  "Kosovo": "xk",
  "Kuwait": "kw",
  "Kyrgyzstan": "kg",
  "Laos": "la",
  "Latvia": "lv",
  "Lebanon": "lb",
  "Liberia": "lr",
  "Libya": "ly",
  "Liechtenstein": "li",
  "Lithuania": "lt",
  "Luxembourg": "lu",
  "Macau": "mo",
  "Madagascar": "mg",
  "Malawi": "mw",
  "Malaysia": "my",
  "Mali": "ml",
  "Malta": "mt",
  "Marruecos": "ma",
  "Martinique": "mq",
  "Mauritania": "mr",
  "Mauritius": "mu",
  "Mexico": "mx",
  "Moldova": "md",
  "Mongolia": "mn",
  "Montenegro": "me",
  "Montserrat": "ms",
  "Morocco": "ma",
  "Mozambique": "mz",
  "Myanmar": "mm",
  "México": "mx",
  "Namibia": "na",
  "Nepal": "np",
  "Netherlands": "nl",
  "New Caledonia": "nc",
  "New Zealand": "nz",
  "Nicaragua": "ni",
  "Niger": "ne",
  "Nigeria": "ng",
  "North Macedonia": "mk",
  "Northern Ireland": "gb-nir",
  "Noruega": "no",
  "Norway": "no",
  "Oman": "om",
  "Pakistan": "pk",
  "Palestine": "ps",
  "Panama": "pa",
  "Panamá": "pa",
  "Papua New Guinea": "pg",
  "Paraguay": "py",
  "Países Bajos": "nl",
  "Peru": "pe",
  "Perú": "pe",
  "Philippines": "ph",
  "Poland": "pl",
  "Polonia": "pl",
  "Portugal": "pt",
  "Puerto Rico": "pr",
  "Qatar": "qa",
  "Republic of Ireland": "ie",
  "Romania": "ro",
  "Rumania": "ro",
  "Rusia": "ru",
  "Russia": "ru",
  "Rwanda": "rw",
  "Saint Kitts and Nevis": "kn",
  "Saint Lucia": "lc",
  "Samoa": "ws",
  "San Marino": "sm",
  "Sao Tome and Principe": "st",
  "Saudi Arabia": "sa",
  "Scotland": "gb-sct",
  "Senegal": "sn",
  "Serbia": "rs",
  "Seychelles": "sc",
  "Sierra Leone": "sl",
  "Singapore": "sg",
  "Slovakia": "sk",
  "Slovenia": "si",
  "Solomon Islands": "sb",
  "Somalia": "so",
  "South Africa": "za",
  "South Sudan": "ss",
  "Spain": "es",
  "Sri Lanka": "lk",
  "St Kitts Nevis": "kn",
  "St Lucia": "lc",
  "Sudan": "sd",
  "Suecia": "se",
  "Suiza": "ch",
  "Suriname": "sr",
  "Sweden": "se",
  "Switzerland": "ch",
  "Syria": "sy",
  "São Tomé & Príncipe": "st",
  "Tahiti": "pf",
  "Tanzania": "tz",
  "Thailand": "th",
  "Togo": "tg",
  "Trinidad and Tobago": "tt",
  "Tunisia": "tn",
  "Turkey": "tr",
  "Turquía": "tr",
  "Ucrania": "ua",
  "Uganda": "ug",
  "Ukraine": "ua",
  "United Arab Emirates": "ae",
  "United States": "us",
  "Uruguay": "uy",
  "Uzbekistan": "uz",
  "Vanuatu": "vu",
  "Venezuela": "ve",
  "Vietnam": "vn",
  "Wales": "gb-wls",
  "Yemen": "ye",
  "Zambia": "zm",
  "Zimbabwe": "zw",
};

/** Código de bandera de un país, o null si no se reconoce. */
export function flagCode(nation?: string | null): string | null {
  if (!nation) return null;
  return CODES[nation.trim()] ?? null;
}

/** Ruta del SVG de la bandera, o null si no hay. */
export function flagSrc(nation?: string | null): string | null {
  const code = flagCode(nation);
  return code ? `/flags/${code}.svg` : null;
}

/**
 * Emoji de bandera. Se mantiene para los espacios muy chicos donde una
 * imagen sería demasiado; para todo lo demás conviene <Flag>.
 */
export function flagEmoji(nation?: string | null): string {
  const code = flagCode(nation);
  if (!code || code.length !== 2) return "🌐";
  return String.fromCodePoint(
    ...code.toUpperCase().split("").map((c) => 0x1f1e6 + c.charCodeAt(0) - 65)
  );
}

/** Nombre de liga acortado para la interfaz. */
export function shortLeague(league?: string | null): string {
  if (!league) return "—";
  return league
    .replace("English Premier League", "Premier League")
    .replace("Spain Primera Division", "LaLiga")
    .replace("Italian Serie A", "Serie A")
    .replace("German 1. Bundesliga", "Bundesliga")
    .replace("French Ligue 1", "Ligue 1")
    .replace("Argentina Primera División", "Liga Argentina")
    .replace("USA Major League Soccer", "MLS")
    .replace("Portuguese Liga ZON SAGRES", "Liga Portugal")
    .replace("Holland Eredivisie", "Eredivisie");
}
